name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: 40.82.138.94
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/azureuser/my-angular-app/dist/my-angular-app/browser/* /var/www/html/
            sudo systemctl restart nginx
